# Generated by Django 4.1.6 on 2023-02-05 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("content", models.BinaryField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("content", models.TextField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
